name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - feature/*
      - release/*
      - hotfix/*
  paths:
    exclude:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - TESTING.md
      - CONTRIBUTING.md
      - .foodcritic
      - .rspec
      - .rubocop.yml
      - .gitignore
      - chefignore

pr:
  branches:
    include:
      - master
      - develop
      - release/*
  paths:
    exclude:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - TESTING.md
      - CONTRIBUTING.md
      - .foodcritic
      - .rspec
      - .rubocop.yml
      - .gitignore
      - chefignore

resources:
  repositories:
    - repository: templates
      type: git
      name: chef-pipelines-templates

jobs:
  - template: common.yml@templates
    parameters:
      kitchenFile: kitchen.yml
      platforms:
        - ubuntu1804
      suites:
        - linux-basic
